### ISSUE TITLE
can't pip install pythia-datasets

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-datasets#3]
Instructions in our README suggest doing
```
python -m pip install pythia-datasets
```
to install into current environment.

That doesn't currently work, as this package has not yet been published on pypi.

**Comment by andersy005** [comment]
@brian-rose, I just published the first version to PyPI: https://pypi.org/project/pythia-datasets/. Give it a try when you get a moment

**Comment by brian-rose** [comment]
Ok, I just installed with pip into a test environment, and everything worked as advertised!
